### ISSUE TITLE
RSS feeds without author information

### ISSUE THREAD

**Issue by dpshelio** [shibasisp/shibasisp.github.io#1]
@shibasisp  - your rss feed doesn't contain author information. Normally, this should be encoded as: 
```python
{   'author': 'myname',
    'author_detail': {'name': 'myname'},
    'authors': [{'name': 'myname'}],
```
when read it with: `feedparser.parse(rss_feed)`.

We need that for the OpenAstronomy blog, so we know it's you :)

**Comment by dpshelio** [comment]
better, as my script is not too general, be sure that you includes the: `'author_detal': {'name': 'myname'}` bit.
Thanks!

**Comment by shibasisp** [comment]
@dpshelio I have updated my feed. Is it okay now?

**Comment by dpshelio** [comment]
I'm getting an empty one:
I would expect this:
```python
    'author_detail': {'name': 'shibasisp'},
```
but I'm getting:
```python
    'author_detail': '',
```

**Comment by dpshelio** [comment]
If you want to test it, you can run `python grab.py` after uncomment your name from `gsoc.yml` in the [OA universe](https://github.com/openastronomy/Universe_OA/) repo.

**Comment by shibasisp** [comment]
@dpshelio updated. please check it.

**Comment by dpshelio** [comment]
Yay! It's working! Well done!! 🎉
